server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres.mau.se:55432/ao7206
    username: ao7206
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ao7206
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect





perenual:
  base-url: https://perenual.com/api/v2
  api-key: ${PERENUAL_API_KEY}